# Generated by Django 5.2.5 on 2025-08-21 03:23

import secured_fields.fields
import secured_fields.fields.files
import secured_fields.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=secured_fields.fields.files.EncryptedFileField(storage=secured_fields.storage.EncryptedFileSystemStorage(), upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=secured_fields.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=secured_fields.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=secured_fields.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=secured_fields.fields.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=secured_fields.fields.EncryptedCharField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=secured_fields.fields.EncryptedCharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=secured_fields.fields.EncryptedCharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=secured_fields.fields.EncryptedCharField(max_length=15),
        ),
    ]
